const CAR_ACTION_TYPES = {
  GET_CAR_LIST_SUCCESS: "GET_CAR_LIST_SUCCESS",
  GET_CAR_LIST_LOADING: "GET_CAR_LIST_LOADING",
  GET_CAR_LIST_ERROR: "GET_CAR_LIST_ERROR",

  FIND_CAR_DETAIL: "FIND_CAR_DETAIL",
};

export { CAR_ACTION_TYPES };
